# Generated by Django 4.1.7 on 2023-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
